#############################################################################
# Generated by PAGE version 6.0
#  in conjunction with Tcl version 8.6
#  Nov 29, 2020 01:50:35 PM IST  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top65 {base} {
    global vTcl
    if {$base == ""} {
        set base .top65
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1425x690+66+171
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra66 \
        -borderwidth 2 -relief groove -background #8e8eff -height 513 \
        -highlightcolor black -width 812 
    vTcl:DefineAlias "$top.fra66" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra66
    listbox $site_3_0.lis91 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -height 427 -highlightcolor black -selectbackground blue \
        -selectforeground white -width 854 
    $site_3_0.lis91 configure -font "TkFixedFont"
    $site_3_0.lis91 insert end text
    vTcl:DefineAlias "$site_3_0.lis91" "listbox_UI" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lis91 \
        -in $site_3_0 -x 0 -relx 0.011 -y 0 -rely 0.137 -width 0 \
        -relwidth 0.978 -height 0 -relheight 0.834 -anchor nw \
        -bordermode ignore 
    frame $top.fra68 \
        -borderwidth 2 -relief groove -background #ff80ff -height 404 \
        -highlightcolor black -width 468 
    vTcl:DefineAlias "$top.fra68" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra68
    label $site_3_0.lab70 \
        -activebackground #f9f9f9 -activeforeground black -background #fb173f \
        -font {-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Add Worker} 
    vTcl:DefineAlias "$site_3_0.lab70" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab71 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Last Name :} 
    vTcl:DefineAlias "$site_3_0.lab71" "Label3" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but79 \
        -background #008200 \
        -font {-family {Segoe UI} -size 18 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightcolor black -pady 0 -text SUBMIT 
    vTcl:DefineAlias "$site_3_0.but79" "add_submit_UI" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab81 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Role  :} 
    vTcl:DefineAlias "$site_3_0.lab81" "Label7" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab82 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {First Name :} 
    vTcl:DefineAlias "$site_3_0.lab82" "Label8" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab83 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Experience :} 
    vTcl:DefineAlias "$site_3_0.lab83" "Label9" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab84 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Segoe UI} -size 16 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Salary in Rs. :} 
    vTcl:DefineAlias "$site_3_0.lab84" "Label10" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent85 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 194 
    vTcl:DefineAlias "$site_3_0.ent85" "add_fname_UI" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent86 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 194 
    vTcl:DefineAlias "$site_3_0.ent86" "add_lname_UI" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent88 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 194 
    vTcl:DefineAlias "$site_3_0.ent88" "add_role_UI" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent89 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 194 
    vTcl:DefineAlias "$site_3_0.ent89" "add_experience_UI" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent90 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 194 
    vTcl:DefineAlias "$site_3_0.ent90" "add_salary_UI" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab70 \
        -in $site_3_0 -x 0 -relx 0.171 -y 0 -rely 0.025 -width 0 \
        -relwidth 0.632 -height 0 -relheight 0.114 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab71 \
        -in $site_3_0 -x 0 -relx 0.085 -y 0 -rely 0.297 -width 0 \
        -relwidth 0.303 -height 0 -relheight 0.092 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but79 \
        -in $site_3_0 -x 0 -relx 0.278 -y 0 -rely 0.866 -width 196 \
        -relwidth 0 -height 43 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab81 \
        -in $site_3_0 -x 0 -relx 0.099 -y 0 -rely 0.421 -width 0 \
        -relwidth 0.282 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab82 \
        -in $site_3_0 -x 0 -relx 0.085 -y 0 -rely 0.173 -width 0 \
        -relwidth 0.303 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab83 \
        -in $site_3_0 -x 0 -relx 0.08 -y 0 -rely 0.569 -width 0 \
        -relwidth 0.302 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab84 \
        -in $site_3_0 -x 0 -relx 0.08 -y 0 -rely 0.718 -width 0 \
        -relwidth 0.324 -height 0 -relheight 0.089 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent85 \
        -in $site_3_0 -x 0 -relx 0.449 -y 0 -rely 0.173 -width 194 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent86 \
        -in $site_3_0 -x 0 -relx 0.449 -y 0 -rely 0.297 -width 194 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent88 \
        -in $site_3_0 -x 0 -relx 0.457 -y 0 -rely 0.421 -width 194 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent89 \
        -in $site_3_0 -x 0 -relx 0.457 -y 0 -rely 0.569 -width 194 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent90 \
        -in $site_3_0 -x 0 -relx 0.457 -y 0 -rely 0.718 -width 194 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra69 \
        -borderwidth 2 -relief groove -background #a6a653 -height 207 \
        -highlightcolor black -width 341 
    vTcl:DefineAlias "$top.fra69" "Frame3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra69
    label $site_3_0.lab72 \
        -activebackground #f9f9f9 -activeforeground black -background #fb173f \
        -font {-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Delete Worker} 
    vTcl:DefineAlias "$site_3_0.lab72" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab73 \
        -activebackground #f9f9f9 -activeforeground black -background #80ffff \
        -font {-family {Segoe UI} -size 15 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Worker's ID  :} 
    vTcl:DefineAlias "$site_3_0.lab73" "Label5" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but74 \
        -background #008200 \
        -font {-family {Segoe UI} -size 18 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightcolor black -pady 0 -text SUBMIT 
    vTcl:DefineAlias "$site_3_0.but74" "del_submit_UI" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent75 \
        -background #80ffff -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 174 
    vTcl:DefineAlias "$site_3_0.ent75" "del_id_UI" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab72 \
        -in $site_3_0 -x 0 -relx 0.146 -y 0 -rely 0.097 -width 0 \
        -relwidth 0.678 -height 0 -relheight 0.222 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab73 \
        -in $site_3_0 -x 0 -relx 0.088 -y 0 -rely 0.435 -width 0 \
        -relwidth 0.364 -height 0 -relheight 0.174 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but74 \
        -in $site_3_0 -x 0 -relx 0.281 -y 0 -rely 0.676 -width 196 \
        -relwidth 0 -height 43 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent75 \
        -in $site_3_0 -x 0 -relx 0.581 -y 0 -rely 0.435 -width 174 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab77 \
        -activebackground #f9f9f9 -activeforeground black -background #c0c0c0 \
        -font {-family {Segoe UI} -size 24 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #99004d -highlightcolor black -text WORKERS 
    vTcl:DefineAlias "$top.lab77" "Label1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but78 \
        -background #ef053a \
        -font {-family {Segoe UI} -size 17 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -pady 0 \
        -text BACK 
    vTcl:DefineAlias "$top.but78" "back_UI" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra45 \
        -borderwidth 2 -relief groove -background #ffff80 -height 125 \
        -highlightbackground #c0c0c0 -highlightcolor black -width 486 
    vTcl:DefineAlias "$top.fra45" "Frame4" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra45
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black -background #ff0000 \
        -font {-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text Attendance 
    vTcl:DefineAlias "$site_3_0.lab47" "Label11" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but48 \
        -background #008040 \
        -font {-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightcolor black -pady 0 -text Reset 
    vTcl:DefineAlias "$site_3_0.but48" "att_reset_UI" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black -background #80ff80 \
        -font {-family {Segoe UI} -size 20 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Worker ID} 
    vTcl:DefineAlias "$site_3_0.lab49" "Label12" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but50 \
        -background #008040 \
        -font {-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightcolor black -pady 0 -text Submit 
    vTcl:DefineAlias "$site_3_0.but50" "att_submit_UI" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent51 \
        -background white -font TkFixedFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -insertbackground black -selectbackground blue \
        -selectforeground white -width 134 
    vTcl:DefineAlias "$site_3_0.ent51" "att_workerid_UI" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but70 \
        -activebackground #f9f9f9 -activeforeground black -background #008040 \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightcolor black -pady 0 -text {Reset Month} 
    vTcl:DefineAlias "$site_3_0.but70" "att_resetmonth_UI" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.021 -y 0 -rely 0.08 -width 0 \
        -relwidth 0.335 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 0 -relx 0.741 -y 0 -rely 0.08 -width 112 -relwidth 0 \
        -height 43 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.041 -y 0 -rely 0.56 -width 0 \
        -relwidth 0.317 -height 0 -relheight 0.248 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 0 -relx 0.741 -y 0 -rely 0.56 -width 112 -relwidth 0 \
        -height 43 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent51 \
        -in $site_3_0 -x 0 -relx 0.412 -y 0 -rely 0.56 -width 134 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but70 \
        -in $site_3_0 -x 0 -relx 0.412 -y 0 -rely 0.08 -width 112 -relwidth 0 \
        -height 43 -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra66 \
        -in $top -x 0 -relx 0.008 -y 0 -rely 0.217 -width 0 -relwidth 0.612 \
        -height 0 -relheight 0.742 -anchor nw -bordermode ignore 
    place $top.fra68 \
        -in $top -x 0 -relx 0.636 -y 0 -rely 0.029 -width 0 -relwidth 0.353 \
        -height 0 -relheight 0.586 -anchor nw -bordermode ignore 
    place $top.fra69 \
        -in $top -x 0 -relx 0.636 -y 0 -rely 0.652 -width 0 -relwidth 0.35 \
        -height 0 -relheight 0.3 -anchor nw -bordermode ignore 
    place $top.lab77 \
        -in $top -x 0 -relx 0.028 -y 0 -rely 0.014 -width 0 -relwidth 0.237 \
        -height 0 -relheight 0.125 -anchor nw -bordermode ignore 
    place $top.but78 \
        -in $top -x 0 -relx 0.028 -y 0 -rely 0.145 -width 116 -relwidth 0 \
        -height 43 -relheight 0 -anchor nw -bordermode ignore 
    place $top.fra45 \
        -in $top -x 0 -relx 0.274 -y 0 -rely 0.014 -width 0 -relwidth 0.341 \
        -height 0 -relheight 0.181 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top65 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

