#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 20, 2020 08:41:20 AM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import EXPENSES SDP RMS_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    EXPENSES SDP RMS_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    EXPENSES SDP RMS_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("905x729+369+93")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#80ffff")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.011, rely=0.014, height=56, width=272)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#4f9d9d")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 20 -weight bold")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''EXPENSES(In Rs.)''')

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.552, rely=0.082, relheight=0.635
                , relwidth=0.432)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#808040")
        self.Frame1.configure(cursor="fleur")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Label7_1 = tk.Label(self.Frame1)
        self.Label7_1.place(relx=0.066, rely=0.028, height=47, width=118)
        self.Label7_1.configure(activebackground="#f9f9f9")
        self.Label7_1.configure(activeforeground="black")
        self.Label7_1.configure(background="#e1031e")
        self.Label7_1.configure(disabledforeground="#a3a3a3")
        self.Label7_1.configure(font="-family {Segoe UI} -size 18 -weight bold")
        self.Label7_1.configure(foreground="#000000")
        self.Label7_1.configure(highlightbackground="#d9d9d9")
        self.Label7_1.configure(highlightcolor="black")
        self.Label7_1.configure(text='''ADD''')

        self.Label8_1 = tk.Label(self.Frame1)
        self.Label8_1.place(relx=0.097, rely=0.164, height=40, width=131)
        self.Label8_1.configure(activebackground="#f9f9f9")
        self.Label8_1.configure(activeforeground="black")
        self.Label8_1.configure(background="#d9d9d9")
        self.Label8_1.configure(disabledforeground="#a3a3a3")
        self.Label8_1.configure(font="-family {Segoe UI} -size 13 -weight bold")
        self.Label8_1.configure(foreground="#000000")
        self.Label8_1.configure(highlightbackground="#d9d9d9")
        self.Label8_1.configure(highlightcolor="black")
        self.Label8_1.configure(text='''ID  :''')

        self.Label10_1 = tk.Label(self.Frame1)
        self.Label10_1.place(relx=0.097, rely=0.419, height=40, width=131)
        self.Label10_1.configure(activebackground="#f9f9f9")
        self.Label10_1.configure(activeforeground="black")
        self.Label10_1.configure(background="#d9d9d9")
        self.Label10_1.configure(disabledforeground="#a3a3a3")
        self.Label10_1.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.Label10_1.configure(foreground="#000000")
        self.Label10_1.configure(highlightbackground="#d9d9d9")
        self.Label10_1.configure(highlightcolor="black")
        self.Label10_1.configure(text='''MONTH  :''')

        self.Label11_1 = tk.Label(self.Frame1)
        self.Label11_1.place(relx=0.097, rely=0.551, height=40, width=131)
        self.Label11_1.configure(activebackground="#f9f9f9")
        self.Label11_1.configure(activeforeground="black")
        self.Label11_1.configure(background="#d9d9d9")
        self.Label11_1.configure(disabledforeground="#a3a3a3")
        self.Label11_1.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.Label11_1.configure(foreground="#000000")
        self.Label11_1.configure(highlightbackground="#d9d9d9")
        self.Label11_1.configure(highlightcolor="black")
        self.Label11_1.configure(text='''DAY No.  :''')

        self.Label11_7 = tk.Label(self.Frame1)
        self.Label11_7.place(relx=0.102, rely=0.683, height=40, width=129)
        self.Label11_7.configure(activebackground="#f9f9f9")
        self.Label11_7.configure(activeforeground="black")
        self.Label11_7.configure(background="#d9d9d9")
        self.Label11_7.configure(disabledforeground="#a3a3a3")
        self.Label11_7.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.Label11_7.configure(foreground="#000000")
        self.Label11_7.configure(highlightbackground="#d9d9d9")
        self.Label11_7.configure(highlightcolor="black")
        self.Label11_7.configure(text='''TYPE/REASON:''')

        self.Label11_8 = tk.Label(self.Frame1)
        self.Label11_8.place(relx=0.097, rely=0.285, height=40, width=131)
        self.Label11_8.configure(activebackground="#f9f9f9")
        self.Label11_8.configure(activeforeground="black")
        self.Label11_8.configure(background="#d9d9d9")
        self.Label11_8.configure(disabledforeground="#a3a3a3")
        self.Label11_8.configure(font="-family {Segoe UI} -size 13 -weight bold")
        self.Label11_8.configure(foreground="#000000")
        self.Label11_8.configure(highlightbackground="#d9d9d9")
        self.Label11_8.configure(highlightcolor="black")
        self.Label11_8.configure(text='''YEAR  :''')

        self.Label11_9 = tk.Label(self.Frame1)
        self.Label11_9.place(relx=0.107, rely=0.793, height=40, width=130)
        self.Label11_9.configure(activebackground="#f9f9f9")
        self.Label11_9.configure(activeforeground="black")
        self.Label11_9.configure(background="#d9d9d9")
        self.Label11_9.configure(disabledforeground="#a3a3a3")
        self.Label11_9.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.Label11_9.configure(foreground="#000000")
        self.Label11_9.configure(highlightbackground="#d9d9d9")
        self.Label11_9.configure(highlightcolor="black")
        self.Label11_9.configure(text='''NOTE  :''')

        self.submit_add_UI = tk.Button(self.Frame1)
        self.submit_add_UI.place(relx=0.332, rely=0.886, height=43, width=146)
        self.submit_add_UI.configure(activebackground="#ececec")
        self.submit_add_UI.configure(activeforeground="#000000")
        self.submit_add_UI.configure(background="#0000ff")
        self.submit_add_UI.configure(disabledforeground="#a3a3a3")
        self.submit_add_UI.configure(font="-family {Segoe UI} -size 18 -weight bold")
        self.submit_add_UI.configure(foreground="#ffffff")
        self.submit_add_UI.configure(highlightbackground="#d9d9d9")
        self.submit_add_UI.configure(highlightcolor="black")
        self.submit_add_UI.configure(pady="0")
        self.submit_add_UI.configure(text='''SUBMIT''')

        self.ID_UI = tk.Entry(self.Frame1)
        self.ID_UI.place(relx=0.46, rely=0.175, height=34, relwidth=0.496)
        self.ID_UI.configure(background="white")
        self.ID_UI.configure(disabledforeground="#a3a3a3")
        self.ID_UI.configure(font="TkFixedFont")
        self.ID_UI.configure(foreground="#000000")
        self.ID_UI.configure(highlightbackground="#d9d9d9")
        self.ID_UI.configure(highlightcolor="black")
        self.ID_UI.configure(insertbackground="black")
        self.ID_UI.configure(selectbackground="blue")
        self.ID_UI.configure(selectforeground="white")

        self.year_UI = tk.Entry(self.Frame1)
        self.year_UI.place(relx=0.455, rely=0.285, height=34, relwidth=0.496)
        self.year_UI.configure(background="white")
        self.year_UI.configure(cursor="fleur")
        self.year_UI.configure(disabledforeground="#a3a3a3")
        self.year_UI.configure(font="TkFixedFont")
        self.year_UI.configure(foreground="#000000")
        self.year_UI.configure(highlightbackground="#d9d9d9")
        self.year_UI.configure(highlightcolor="black")
        self.year_UI.configure(insertbackground="black")
        self.year_UI.configure(selectbackground="blue")
        self.year_UI.configure(selectforeground="white")

        self.month_UI = tk.Entry(self.Frame1)
        self.month_UI.place(relx=0.455, rely=0.419, height=34, relwidth=0.496)
        self.month_UI.configure(background="white")
        self.month_UI.configure(disabledforeground="#a3a3a3")
        self.month_UI.configure(font="TkFixedFont")
        self.month_UI.configure(foreground="#000000")
        self.month_UI.configure(highlightbackground="#d9d9d9")
        self.month_UI.configure(highlightcolor="black")
        self.month_UI.configure(insertbackground="black")
        self.month_UI.configure(selectbackground="blue")
        self.month_UI.configure(selectforeground="white")

        self.day_UI = tk.Entry(self.Frame1)
        self.day_UI.place(relx=0.458, rely=0.551, height=34, relwidth=0.496)
        self.day_UI.configure(background="white")
        self.day_UI.configure(disabledforeground="#a3a3a3")
        self.day_UI.configure(font="TkFixedFont")
        self.day_UI.configure(foreground="#000000")
        self.day_UI.configure(highlightbackground="#d9d9d9")
        self.day_UI.configure(highlightcolor="black")
        self.day_UI.configure(insertbackground="black")
        self.day_UI.configure(selectbackground="blue")
        self.day_UI.configure(selectforeground="white")

        self.type_UI = tk.Entry(self.Frame1)
        self.type_UI.place(relx=0.458, rely=0.683, height=34, relwidth=0.496)
        self.type_UI.configure(background="white")
        self.type_UI.configure(disabledforeground="#a3a3a3")
        self.type_UI.configure(font="TkFixedFont")
        self.type_UI.configure(foreground="#000000")
        self.type_UI.configure(highlightbackground="#d9d9d9")
        self.type_UI.configure(highlightcolor="black")
        self.type_UI.configure(insertbackground="black")
        self.type_UI.configure(selectbackground="blue")
        self.type_UI.configure(selectforeground="white")

        self.note_UI = tk.Entry(self.Frame1)
        self.note_UI.place(relx=0.46, rely=0.799, height=34, relwidth=0.496)
        self.note_UI.configure(background="white")
        self.note_UI.configure(disabledforeground="#a3a3a3")
        self.note_UI.configure(font="TkFixedFont")
        self.note_UI.configure(foreground="#000000")
        self.note_UI.configure(highlightbackground="#d9d9d9")
        self.note_UI.configure(highlightcolor="black")
        self.note_UI.configure(insertbackground="black")
        self.note_UI.configure(selectbackground="blue")
        self.note_UI.configure(selectforeground="white")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.63, rely=0.014, height=33, width=96)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#e1031e")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 17 -weight bold")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''BACK''')

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.552, rely=0.727, relheight=0.239
                , relwidth=0.432)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#808040")
        self.Frame2.configure(cursor="fleur")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")

        self.Label7_15 = tk.Label(self.Frame2)
        self.Label7_15.place(relx=0.028, rely=0.063, height=38, width=153)
        self.Label7_15.configure(activebackground="#f9f9f9")
        self.Label7_15.configure(activeforeground="black")
        self.Label7_15.configure(background="#e1031e")
        self.Label7_15.configure(disabledforeground="#a3a3a3")
        self.Label7_15.configure(font="-family {Segoe UI} -size 18 -weight bold")
        self.Label7_15.configure(foreground="#000000")
        self.Label7_15.configure(highlightbackground="#d9d9d9")
        self.Label7_15.configure(highlightcolor="black")
        self.Label7_15.configure(text='''DELETE''')

        self.Label8_16 = tk.Label(self.Frame2)
        self.Label8_16.place(relx=0.082, rely=0.425, height=42, width=124)
        self.Label8_16.configure(activebackground="#f9f9f9")
        self.Label8_16.configure(activeforeground="black")
        self.Label8_16.configure(background="#d9d9d9")
        self.Label8_16.configure(disabledforeground="#a3a3a3")
        self.Label8_16.configure(font="-family {Segoe UI} -size 13 -weight bold")
        self.Label8_16.configure(foreground="#000000")
        self.Label8_16.configure(highlightbackground="#d9d9d9")
        self.Label8_16.configure(highlightcolor="black")
        self.Label8_16.configure(text='''ID  :''')

        self.del_ID_UI = tk.Entry(self.Frame2)
        self.del_ID_UI.place(relx=0.44, rely=0.425, height=34, relwidth=0.496)
        self.del_ID_UI.configure(background="white")
        self.del_ID_UI.configure(disabledforeground="#a3a3a3")
        self.del_ID_UI.configure(font="TkFixedFont")
        self.del_ID_UI.configure(foreground="#000000")
        self.del_ID_UI.configure(highlightbackground="#d9d9d9")
        self.del_ID_UI.configure(highlightcolor="black")
        self.del_ID_UI.configure(insertbackground="black")
        self.del_ID_UI.configure(selectbackground="blue")
        self.del_ID_UI.configure(selectforeground="white")

        self.submit_del_UI = tk.Button(self.Frame2)
        self.submit_del_UI.place(relx=0.332, rely=0.69, height=43, width=156)
        self.submit_del_UI.configure(activebackground="#ececec")
        self.submit_del_UI.configure(activeforeground="#000000")
        self.submit_del_UI.configure(background="#0000ff")
        self.submit_del_UI.configure(disabledforeground="#a3a3a3")
        self.submit_del_UI.configure(font="-family {Segoe UI} -size 18 -weight bold")
        self.submit_del_UI.configure(foreground="#ffffff")
        self.submit_del_UI.configure(highlightbackground="#d9d9d9")
        self.submit_del_UI.configure(highlightcolor="black")
        self.submit_del_UI.configure(pady="0")
        self.submit_del_UI.configure(text='''SUBMIT''')

        self.listbox_UI = tk.Listbox(top)
        self.listbox_UI.place(relx=0.022, rely=0.233, relheight=0.642
                , relwidth=0.502)
        self.listbox_UI.configure(background="white")
        self.listbox_UI.configure(disabledforeground="#a3a3a3")
        self.listbox_UI.configure(font="TkFixedFont")
        self.listbox_UI.configure(foreground="#000000")
        self.listbox_UI.configure(highlightbackground="#d9d9d9")
        self.listbox_UI.configure(highlightcolor="black")
        self.listbox_UI.configure(selectbackground="blue")
        self.listbox_UI.configure(selectforeground="white")

if __name__ == '__main__':
    vp_start_gui()





