#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 20, 2020 08:36:16 AM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Login Page SDP RMS_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    Login Page SDP RMS_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    Login Page SDP RMS_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1065x753+105+143")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=-0.019, rely=-0.013, relheight=1.029
                , relwidth=1.045)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#ff5151")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Frame2 = tk.Frame(self.Frame1)
        self.Frame2.place(relx=0.081, rely=0.103, relheight=0.794
                , relwidth=0.832)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#00a800")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")

        self.Frame3 = tk.Frame(self.Frame2)
        self.Frame3.place(relx=0.076, rely=0.114, relheight=0.772
                , relwidth=0.849)
        self.Frame3.configure(relief='groove')
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief="groove")
        self.Frame3.configure(background="#d7d700")
        self.Frame3.configure(highlightbackground="#d9d9d9")
        self.Frame3.configure(highlightcolor="black")

        self.Frame4 = tk.Frame(self.Frame3)
        self.Frame4.place(relx=0.076, rely=0.126, relheight=0.768
                , relwidth=0.846)
        self.Frame4.configure(relief='groove')
        self.Frame4.configure(borderwidth="2")
        self.Frame4.configure(relief="groove")
        self.Frame4.configure(background="#808080")
        self.Frame4.configure(highlightbackground="#d9d9d9")
        self.Frame4.configure(highlightcolor="black")

        self.Label1 = tk.Label(self.Frame4)
        self.Label1.place(relx=0.075, rely=0.055, height=56, width=582)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 22 -weight bold")
        self.Label1.configure(foreground="#910b6e")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Restaurant Management Sysytem''')

        self.Label2_1 = tk.Label(self.Frame4)
        self.Label2_1.place(relx=0.135, rely=0.301, height=36, width=162)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#d9d9d9")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font="-family {Segoe UI} -size 15")
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''Username  :''')

        self.Label3_1 = tk.Label(self.Frame4)
        self.Label3_1.place(relx=0.135, rely=0.493, height=36, width=162)
        self.Label3_1.configure(activebackground="#f9f9f9")
        self.Label3_1.configure(activeforeground="black")
        self.Label3_1.configure(background="#d9d9d9")
        self.Label3_1.configure(disabledforeground="#a3a3a3")
        self.Label3_1.configure(font="-family {Segoe UI} -size 15")
        self.Label3_1.configure(foreground="#000000")
        self.Label3_1.configure(highlightbackground="#d9d9d9")
        self.Label3_1.configure(highlightcolor="black")
        self.Label3_1.configure(text='''Password  :''')

        self.username_UI = tk.Entry(self.Frame4)
        self.username_UI.place(relx=0.436, rely=0.301, height=34, relwidth=0.367)

        self.username_UI.configure(background="#d8d8d8")
        self.username_UI.configure(disabledforeground="#a3a3a3")
        self.username_UI.configure(font="TkFixedFont")
        self.username_UI.configure(foreground="#000000")
        self.username_UI.configure(highlightbackground="#d9d9d9")
        self.username_UI.configure(highlightcolor="black")
        self.username_UI.configure(insertbackground="black")
        self.username_UI.configure(selectbackground="blue")
        self.username_UI.configure(selectforeground="white")

        self.pass_UI = tk.Entry(self.Frame4)
        self.pass_UI.place(relx=0.436, rely=0.493, height=34, relwidth=0.367)
        self.pass_UI.configure(background="#d7d7d7")
        self.pass_UI.configure(disabledforeground="#a3a3a3")
        self.pass_UI.configure(font="TkFixedFont")
        self.pass_UI.configure(foreground="#000000")
        self.pass_UI.configure(highlightbackground="#d9d9d9")
        self.pass_UI.configure(highlightcolor="black")
        self.pass_UI.configure(insertbackground="black")
        self.pass_UI.configure(selectbackground="blue")
        self.pass_UI.configure(selectforeground="white")

        self.billing_UI = tk.Button(self.Frame4)
        self.billing_UI.place(relx=0.15, rely=0.658, height=43, width=156)
        self.billing_UI.configure(activebackground="#ececec")
        self.billing_UI.configure(activeforeground="#000000")
        self.billing_UI.configure(background="#ff0000")
        self.billing_UI.configure(disabledforeground="#a3a3a3")
        self.billing_UI.configure(font="-family {Segoe UI} -size 18")
        self.billing_UI.configure(foreground="#000000")
        self.billing_UI.configure(highlightbackground="#d9d9d9")
        self.billing_UI.configure(highlightcolor="black")
        self.billing_UI.configure(pady="0")
        self.billing_UI.configure(text='''BILLING''')

        self.workers_UI = tk.Button(self.Frame4)
        self.workers_UI.place(relx=0.541, rely=0.658, height=43, width=156)
        self.workers_UI.configure(activebackground="#ececec")
        self.workers_UI.configure(activeforeground="#000000")
        self.workers_UI.configure(background="#1515ff")
        self.workers_UI.configure(disabledforeground="#a3a3a3")
        self.workers_UI.configure(font="-family {Segoe UI} -size 18")
        self.workers_UI.configure(foreground="#000000")
        self.workers_UI.configure(highlightbackground="#d9d9d9")
        self.workers_UI.configure(highlightcolor="black")
        self.workers_UI.configure(pady="0")
        self.workers_UI.configure(text='''WORKERS''')

        self.maintenence_UI = tk.Button(self.Frame4)
        self.maintenence_UI.place(relx=0.15, rely=0.849, height=43, width=216)
        self.maintenence_UI.configure(activebackground="#ececec")
        self.maintenence_UI.configure(activeforeground="#000000")
        self.maintenence_UI.configure(background="#0000ff")
        self.maintenence_UI.configure(cursor="fleur")
        self.maintenence_UI.configure(disabledforeground="#a3a3a3")
        self.maintenence_UI.configure(font="-family {Segoe UI} -size 18")
        self.maintenence_UI.configure(foreground="#000000")
        self.maintenence_UI.configure(highlightbackground="#d9d9d9")
        self.maintenence_UI.configure(highlightcolor="black")
        self.maintenence_UI.configure(pady="0")
        self.maintenence_UI.configure(text='''MAINTENANCE''')

        self.expenses_UI = tk.Button(self.Frame4)
        self.expenses_UI.place(relx=0.541, rely=0.849, height=43, width=156)
        self.expenses_UI.configure(activebackground="#ececec")
        self.expenses_UI.configure(activeforeground="#000000")
        self.expenses_UI.configure(background="#ff0000")
        self.expenses_UI.configure(disabledforeground="#a3a3a3")
        self.expenses_UI.configure(font="-family {Segoe UI} -size 18")
        self.expenses_UI.configure(foreground="#000000")
        self.expenses_UI.configure(highlightbackground="#d9d9d9")
        self.expenses_UI.configure(highlightcolor="black")
        self.expenses_UI.configure(pady="0")
        self.expenses_UI.configure(text='''EXPENSES''')

        self.exporttoexcel_UI = tk.Button(self.Frame2)
        self.exporttoexcel_UI.place(relx=0.648, rely=0.894, height=53, width=286)

        self.exporttoexcel_UI.configure(activebackground="#ececec")
        self.exporttoexcel_UI.configure(activeforeground="#000000")
        self.exporttoexcel_UI.configure(background="#408080")
        self.exporttoexcel_UI.configure(disabledforeground="#a3a3a3")
        self.exporttoexcel_UI.configure(font="-family {Segoe UI} -size 18 -weight bold")
        self.exporttoexcel_UI.configure(foreground="#000000")
        self.exporttoexcel_UI.configure(highlightbackground="#d9d9d9")
        self.exporttoexcel_UI.configure(highlightcolor="black")
        self.exporttoexcel_UI.configure(pady="0")
        self.exporttoexcel_UI.configure(text='''EXPORT TO EXCEL''')

if __name__ == '__main__':
    vp_start_gui()





