#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.6
#  in conjunction with Tcl version 8.6
#    Nov 20, 2020 08:45:38 AM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import MAINTENANCE SD RMS_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    MAINTENANCE SD RMS_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    MAINTENANCE SD RMS_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("902x716+398+158")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(background="#ff8f59")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.033, rely=0.042, height=46, width=222)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 18 -weight bold")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''MAINTENANCE''')

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.599, rely=0.14, relheight=0.468, relwidth=0.382)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#ff80ff")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Label2_1 = tk.Label(self.Frame1)
        self.Label2_1.place(relx=0.348, rely=0.03, height=40, width=92)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(activeforeground="black")
        self.Label2_1.configure(background="#ff0000")
        self.Label2_1.configure(disabledforeground="#a3a3a3")
        self.Label2_1.configure(font="-family {Segoe UI} -size 17 -weight bold")
        self.Label2_1.configure(foreground="#000000")
        self.Label2_1.configure(highlightbackground="#d9d9d9")
        self.Label2_1.configure(highlightcolor="black")
        self.Label2_1.configure(text='''ADD''')

        self.Label4_2 = tk.Label(self.Frame1)
        self.Label4_2.place(relx=0.058, rely=0.179, height=32, width=122)
        self.Label4_2.configure(activebackground="#f9f9f9")
        self.Label4_2.configure(activeforeground="black")
        self.Label4_2.configure(background="#d9d9d9")
        self.Label4_2.configure(disabledforeground="#a3a3a3")
        self.Label4_2.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.Label4_2.configure(foreground="#000000")
        self.Label4_2.configure(highlightbackground="#d9d9d9")
        self.Label4_2.configure(highlightcolor="black")
        self.Label4_2.configure(text='''TYPE  :''')

        self.Label5_3 = tk.Label(self.Frame1)
        self.Label5_3.place(relx=0.058, rely=0.328, height=32, width=122)
        self.Label5_3.configure(activebackground="#f9f9f9")
        self.Label5_3.configure(activeforeground="black")
        self.Label5_3.configure(background="#d9d9d9")
        self.Label5_3.configure(disabledforeground="#a3a3a3")
        self.Label5_3.configure(font="-family {Segoe UI} -size 11 -weight bold")
        self.Label5_3.configure(foreground="#000000")
        self.Label5_3.configure(highlightbackground="#d9d9d9")
        self.Label5_3.configure(highlightcolor="black")
        self.Label5_3.configure(text='''NAME ID  :''')

        self.Label7_4 = tk.Label(self.Frame1)
        self.Label7_4.place(relx=0.0, rely=0.478, height=32, width=152)
        self.Label7_4.configure(activebackground="#f9f9f9")
        self.Label7_4.configure(activeforeground="black")
        self.Label7_4.configure(background="#d9d9d9")
        self.Label7_4.configure(disabledforeground="#a3a3a3")
        self.Label7_4.configure(font="-family {Segoe UI} -size 8 -weight bold")
        self.Label7_4.configure(foreground="#000000")
        self.Label7_4.configure(highlightbackground="#d9d9d9")
        self.Label7_4.configure(highlightcolor="black")
        self.Label7_4.configure(text='''TOTAL EXPENSE IN RS. :''')

        self.Label8_5 = tk.Label(self.Frame1)
        self.Label8_5.place(relx=0.058, rely=0.627, height=32, width=132)
        self.Label8_5.configure(activebackground="#f9f9f9")
        self.Label8_5.configure(activeforeground="black")
        self.Label8_5.configure(background="#d9d9d9")
        self.Label8_5.configure(disabledforeground="#a3a3a3")
        self.Label8_5.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Label8_5.configure(foreground="#000000")
        self.Label8_5.configure(highlightbackground="#d9d9d9")
        self.Label8_5.configure(highlightcolor="black")
        self.Label8_5.configure(text='''DONE OR NOT:''')

        self.submit_add_UI = tk.Button(self.Frame1)
        self.submit_add_UI.place(relx=0.319, rely=0.806, height=33, width=136)
        self.submit_add_UI.configure(activebackground="#ececec")
        self.submit_add_UI.configure(activeforeground="#000000")
        self.submit_add_UI.configure(background="#0000ff")
        self.submit_add_UI.configure(disabledforeground="#a3a3a3")
        self.submit_add_UI.configure(font="-family {Segoe UI} -size 13 -weight bold")
        self.submit_add_UI.configure(foreground="#ffffff")
        self.submit_add_UI.configure(highlightbackground="#d9d9d9")
        self.submit_add_UI.configure(highlightcolor="black")
        self.submit_add_UI.configure(pady="0")
        self.submit_add_UI.configure(text='''SUBMIT''')

        self.type_UI = tk.Entry(self.Frame1)
        self.type_UI.place(relx=0.464, rely=0.179, height=34, relwidth=0.504)
        self.type_UI.configure(background="white")
        self.type_UI.configure(disabledforeground="#a3a3a3")
        self.type_UI.configure(font="TkFixedFont")
        self.type_UI.configure(foreground="#000000")
        self.type_UI.configure(highlightbackground="#d9d9d9")
        self.type_UI.configure(highlightcolor="black")
        self.type_UI.configure(insertbackground="black")
        self.type_UI.configure(selectbackground="blue")
        self.type_UI.configure(selectforeground="white")

        self.nameid_UI = tk.Entry(self.Frame1)
        self.nameid_UI.place(relx=0.464, rely=0.328, height=34, relwidth=0.446)
        self.nameid_UI.configure(background="white")
        self.nameid_UI.configure(disabledforeground="#a3a3a3")
        self.nameid_UI.configure(font="TkFixedFont")
        self.nameid_UI.configure(foreground="#000000")
        self.nameid_UI.configure(highlightbackground="#d9d9d9")
        self.nameid_UI.configure(highlightcolor="black")
        self.nameid_UI.configure(insertbackground="black")
        self.nameid_UI.configure(selectbackground="blue")
        self.nameid_UI.configure(selectforeground="white")

        self.totalexpence_UI = tk.Entry(self.Frame1)
        self.totalexpence_UI.place(relx=0.464, rely=0.478, height=34
                , relwidth=0.475)
        self.totalexpence_UI.configure(background="white")
        self.totalexpence_UI.configure(disabledforeground="#a3a3a3")
        self.totalexpence_UI.configure(font="TkFixedFont")
        self.totalexpence_UI.configure(foreground="#000000")
        self.totalexpence_UI.configure(highlightbackground="#d9d9d9")
        self.totalexpence_UI.configure(highlightcolor="black")
        self.totalexpence_UI.configure(insertbackground="black")
        self.totalexpence_UI.configure(selectbackground="blue")
        self.totalexpence_UI.configure(selectforeground="white")

        self.done_UI = tk.Entry(self.Frame1)
        self.done_UI.place(relx=0.464, rely=0.627, height=34, relwidth=0.475)
        self.done_UI.configure(background="white")
        self.done_UI.configure(disabledforeground="#a3a3a3")
        self.done_UI.configure(font="TkFixedFont")
        self.done_UI.configure(foreground="#000000")
        self.done_UI.configure(highlightbackground="#d9d9d9")
        self.done_UI.configure(highlightcolor="black")
        self.done_UI.configure(insertbackground="black")
        self.done_UI.configure(selectbackground="blue")
        self.done_UI.configure(selectforeground="white")

        self.back_UI = tk.Label(top)
        self.back_UI.place(relx=0.599, rely=0.014, height=36, width=82)
        self.back_UI.configure(activebackground="#f9f9f9")
        self.back_UI.configure(activeforeground="black")
        self.back_UI.configure(background="#0080ff")
        self.back_UI.configure(disabledforeground="#a3a3a3")
        self.back_UI.configure(font="-family {Segoe UI} -size 14 -weight bold")
        self.back_UI.configure(foreground="#ffffff")
        self.back_UI.configure(highlightbackground="#d9d9d9")
        self.back_UI.configure(highlightcolor="black")
        self.back_UI.configure(text='''BACK''')

        self.Label6 = tk.Label(top)
        self.Label6.place(relx=0.033, rely=0.154, height=26, width=339)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#ff00ff")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''NAME ID Eg. M12020 MEANS MONTH 1 OF 2020''')

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.599, rely=0.642, relheight=0.271
                , relwidth=0.386)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#ff80ff")
        self.Frame2.configure(highlightbackground="#d9d9d9")
        self.Frame2.configure(highlightcolor="black")

        self.Label9 = tk.Label(self.Frame2)
        self.Label9.place(relx=0.259, rely=0.093, height=24, width=177)
        self.Label9.configure(activebackground="#f9f9f9")
        self.Label9.configure(activeforeground="black")
        self.Label9.configure(background="#ff0000")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(font="-family {Segoe UI} -size 15 -weight bold")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(highlightbackground="#d9d9d9")
        self.Label9.configure(highlightcolor="black")
        self.Label9.configure(text='''DELETE ENTRY''')

        self.Label10 = tk.Label(self.Frame2)
        self.Label10.place(relx=0.115, rely=0.423, height=33, width=112)
        self.Label10.configure(activebackground="#f9f9f9")
        self.Label10.configure(activeforeground="black")
        self.Label10.configure(background="#d9d9d9")
        self.Label10.configure(disabledforeground="#a3a3a3")
        self.Label10.configure(font="-family {Segoe UI} -size 12 -weight bold")
        self.Label10.configure(foreground="#000000")
        self.Label10.configure(highlightbackground="#d9d9d9")
        self.Label10.configure(highlightcolor="black")
        self.Label10.configure(text='''NAME ID :''')

        self.submit_del_UI = tk.Button(self.Frame2)
        self.submit_del_UI.place(relx=0.345, rely=0.722, height=33, width=126)
        self.submit_del_UI.configure(activebackground="#ececec")
        self.submit_del_UI.configure(activeforeground="#000000")
        self.submit_del_UI.configure(background="#0000ff")
        self.submit_del_UI.configure(disabledforeground="#a3a3a3")
        self.submit_del_UI.configure(font="-family {Segoe UI} -size 13 -weight bold")
        self.submit_del_UI.configure(foreground="#ffffff")
        self.submit_del_UI.configure(highlightbackground="#d9d9d9")
        self.submit_del_UI.configure(highlightcolor="black")
        self.submit_del_UI.configure(pady="0")
        self.submit_del_UI.configure(text='''SUBMIT''')

        self.del_nameid_UI = tk.Entry(self.Frame2)
        self.del_nameid_UI.place(relx=0.517, rely=0.412, height=34
                , relwidth=0.356)
        self.del_nameid_UI.configure(background="white")
        self.del_nameid_UI.configure(disabledforeground="#a3a3a3")
        self.del_nameid_UI.configure(font="TkFixedFont")
        self.del_nameid_UI.configure(foreground="#000000")
        self.del_nameid_UI.configure(highlightbackground="#d9d9d9")
        self.del_nameid_UI.configure(highlightcolor="black")
        self.del_nameid_UI.configure(insertbackground="black")
        self.del_nameid_UI.configure(selectbackground="blue")
        self.del_nameid_UI.configure(selectforeground="white")

        self.listbox_UI = tk.Listbox(top)
        self.listbox_UI.place(relx=0.011, rely=0.335, relheight=0.624
                , relwidth=0.537)
        self.listbox_UI.configure(background="white")
        self.listbox_UI.configure(disabledforeground="#a3a3a3")
        self.listbox_UI.configure(font="TkFixedFont")
        self.listbox_UI.configure(foreground="#000000")
        self.listbox_UI.configure(highlightbackground="#d9d9d9")
        self.listbox_UI.configure(highlightcolor="black")
        self.listbox_UI.configure(selectbackground="blue")
        self.listbox_UI.configure(selectforeground="white")

if __name__ == '__main__':
    vp_start_gui()





