#############     source code                 ##############################
#############     Version 2.0.1               ##############################
#############  RESTAURANT MANAGEMENT SYSTEM   ##############################

# project by -----------
# Pranesh Kulkarni
# Rucha Patil
# Aniket kesarkar
# Ankit lad
# Tanmay Paratkar
# Avishkar kandhare

#-------------------------------------------------------
# Topic : Restaurant Management System using MySQL databases and Tkinter GUI
#---------------------------------------------------------|

#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0
#  in conjunction with Tcl version 8.6
#    Nov 29, 2020 01:09:39 PM IST  platform: Linux

import EXPENSES_RMS
import MAINTENANCE_RMS
import workers_RMS
import billing
from tkinter import messagebox
import mysql.connector
from dbConnect import DBConnect
from openpyxl import Workbook

hostname = 'freedb.tech'
MYSQLusername = 'freedbtech_Aniket'
MYSQLpass = 'Aniket@2000'
dbname = 'freedbtech_RMS'

import sys


try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import App_RMS_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    App_RMS_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    App_RMS_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def exported(self):
        mydb=mysql.connector.connect(host=hostname,user=MYSQLusername,passwd=MYSQLpass,database=dbname)
        mycursor=mydb.cursor()
        wb = Workbook()
        query = 'SELECT * from newhotelpune;'
        mycursor.execute(query)
        results = mycursor.fetchall()
        ws = wb.create_sheet(0)
        ws.title = 'Billing_data'
        ws.append(mycursor.column_names)
        for row in results:
        	ws.append(row)
        	
        

        query = 'SELECT * from Expences;'
        mycursor.execute(query)
        results = mycursor.fetchall()
        ws = wb.create_sheet(0)
        ws.title = 'Expences_data'
        ws.append(mycursor.column_names)
        for row in results:
        	ws.append(row)

        query = 'SELECT * from Maintainance;'
        mycursor.execute(query)
        results = mycursor.fetchall()
        ws = wb.create_sheet(0)
        ws.title = 'Maintainance_data'
        ws.append(mycursor.column_names)
        for row in results:
        	ws.append(row)

        query = 'SELECT * from workers;'
        mycursor.execute(query)
        results = mycursor.fetchall()
        ws = wb.create_sheet(0)
        ws.title = 'workers_data'
        ws.append(mycursor.column_names)
        for row in results:
        	ws.append(row)
        wb.save("DATABASE.xlsx")
	

    def billings(self):
        uname_app = str(self.username_UI.get())
        pass_app = str(self.pass_UI.get())
        if uname_app == 'user' and pass_app == 'pass':
            root.destroy()
            billing.billing()

        else:
            messagebox.showerror("App RMS",'Incorrect Username or Password')


    def workers(self):
        uname_app = str(self.username_UI.get())
        pass_app = str(self.pass_UI.get())
        if uname_app == 'user' and pass_app == 'pass':
            root.destroy()
            workers_RMS.vp_start_gui()
        else:
            messagebox.showerror("App RMS",'Incorrect Username or Password')


    def maintains(self):
        uname_app = str(self.username_UI.get())
        pass_app = str(self.pass_UI.get())
        if uname_app == 'user' and pass_app == 'pass':
            root.destroy()
            MAINTENANCE_RMS.vp_start_gui()
        else:
            messagebox.showerror("App RMS",'Incorrect Username or Password')


    def expences(self):
        uname_app = str(self.username_UI.get())
        pass_app = str(self.pass_UI.get())
        if uname_app == 'user' and pass_app == 'pass':
            root.destroy()
            EXPENSES_RMS.vp_start_gui()
        else:
            messagebox.showerror("App RMS",'Incorrect Username or Password')

    def exports(self):
        uname_app = str(self.username_UI.get())
        pass_app = str(self.pass_UI.get())
        if uname_app == 'user' and pass_app == 'pass':
            self.exported()
            messagebox.showinfo('RMS','Exported.......')
        else:
            messagebox.showerror("App RMS",'Incorrect Username or Password')


    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1065x753+287+61")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1,  1)
        top.title("New Toplevel")
        top.configure(highlightcolor="black")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=-0.019, rely=-0.013, relheight=1.029
                , relwidth=1.045)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#ff5151")

        self.Frame2 = tk.Frame(self.Frame1)
        self.Frame2.place(relx=0.081, rely=0.103, relheight=0.794
                , relwidth=0.832)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#00a800")

        self.Frame3 = tk.Frame(self.Frame2)
        self.Frame3.place(relx=0.076, rely=0.114, relheight=0.772
                , relwidth=0.849)
        self.Frame3.configure(relief='groove')
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief="groove")
        self.Frame3.configure(background="#d7d700")

        self.Frame4 = tk.Frame(self.Frame3)
        self.Frame4.place(relx=0.076, rely=0.126, relheight=0.768
                , relwidth=0.846)
        self.Frame4.configure(relief='groove')
        self.Frame4.configure(borderwidth="2")
        self.Frame4.configure(relief="groove")
        self.Frame4.configure(background="#808080")

        self.Label1 = tk.Label(self.Frame4)
        self.Label1.place(relx=0.075, rely=0.055, height=56, width=582)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(font="-family {Segoe UI} -size 22 -weight bold")
        self.Label1.configure(foreground="#910b6e")
        self.Label1.configure(text='''Restaurant Management Sysytem''')

        self.Label2_1 = tk.Label(self.Frame4)
        self.Label2_1.place(relx=0.135, rely=0.301, height=36, width=162)
        self.Label2_1.configure(activebackground="#f9f9f9")
        self.Label2_1.configure(font="-family {Segoe UI} -size 15")
        self.Label2_1.configure(text='''Username  :''')

        self.Label3_1 = tk.Label(self.Frame4)
        self.Label3_1.place(relx=0.135, rely=0.493, height=36, width=162)
        self.Label3_1.configure(activebackground="#f9f9f9")
        self.Label3_1.configure(font="-family {Segoe UI} -size 15")
        self.Label3_1.configure(text='''Password  :''')

        self.username_UI = tk.Entry(self.Frame4)
        self.username_UI.place(relx=0.436, rely=0.301, height=34, relwidth=0.367)

        self.username_UI.configure(background="#d8d8d8")
        self.username_UI.configure(font="TkFixedFont")
        self.username_UI.configure(selectbackground="blue")
        self.username_UI.configure(selectforeground="white")

        self.pass_UI = tk.Entry(self.Frame4)
        self.pass_UI.place(relx=0.436, rely=0.493, height=34, relwidth=0.367)
        self.pass_UI.configure(background="#d7d7d7")
        self.pass_UI.configure(font="TkFixedFont")
        self.pass_UI.configure(selectbackground="blue")
        self.pass_UI.configure(selectforeground="white")

        self.billing_UI = tk.Button(self.Frame4)
        self.billing_UI.place(relx=0.15, rely=0.658, height=43, width=156)
        self.billing_UI.configure(background="#ff0000")
        self.billing_UI.configure(font="-family {Segoe UI} -size 18")
        self.billing_UI.configure(pady="0")
        self.billing_UI.configure(text='''BILLING''',command = self.billings)

        self.workers_UI = tk.Button(self.Frame4)
        self.workers_UI.place(relx=0.541, rely=0.658, height=43, width=156)
        self.workers_UI.configure(background="#1515ff")
        self.workers_UI.configure(font="-family {Segoe UI} -size 18")
        self.workers_UI.configure(pady="0")
        self.workers_UI.configure(text='''WORKERS''',command = self.workers)

        self.maintenence_UI = tk.Button(self.Frame4)
        self.maintenence_UI.place(relx=0.15, rely=0.849, height=43, width=216)
        self.maintenence_UI.configure(background="#0000ff")
        self.maintenence_UI.configure(font="-family {Segoe UI} -size 18")
        self.maintenence_UI.configure(pady="0")
        self.maintenence_UI.configure(text='''MAINTENANCE''',command = self.maintains)

        self.expenses_UI = tk.Button(self.Frame4)
        self.expenses_UI.place(relx=0.541, rely=0.849, height=43, width=156)
        self.expenses_UI.configure(background="#ff0000")
        self.expenses_UI.configure(font="-family {Segoe UI} -size 18")
        self.expenses_UI.configure(pady="0")
        self.expenses_UI.configure(text='''EXPENSES''',command = self.expences)

        self.exporttoexcel_UI = tk.Button(self.Frame2)
        self.exporttoexcel_UI.place(relx=0.648, rely=0.894, height=53, width=286)

        self.exporttoexcel_UI.configure(background="#408080")
        self.exporttoexcel_UI.configure(font="-family {Segoe UI} -size 18 -weight bold")
        self.exporttoexcel_UI.configure(pady="0")
        self.exporttoexcel_UI.configure(text='''EXPORT TO EXCEL''',command = self.exports)

if __name__ == '__main__':
    vp_start_gui()
